[package]
name = "keylite"
version = "0.1.0"
edition = "2021"

[dependencies]
keylite-core = { path = "../keylite" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
rustyline = "14.0"
