[package]
name = "keylite-db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
keylite-kv = { path = "../kv" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4"] }
